apiVersion: apps/v1
kind: Deployment
metadata:
  name: final-hope
  labels:
    app: final-hope
spec:
  replicas: 1
  selector:
    matchLabels:
      app: final-hope
  template:
    metadata:
      labels:
        app: final-hope
    spec:
      containers:
      - name: final-hope
        image: syeddhasnainn/test:latest  # Make sure this matches your Docker image
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
        
---
apiVersion: v1
kind: Service
metadata:
  name: final-hope
spec:
  selector:
    app: final-hope
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: final-hope
  annotations:
    kubernetes.io/ingress.className: nginx # If using cert-manager for automatic certificate provisioning

spec:
  rules:
  - host: ask1.talaash.app
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: final-hope
            port:
              number: 3000