apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing
spec:
  replicas: 3
  selector:
    matchLabels:
      app: landing
  template:
    metadata:
      labels:
        app: landing
    spec:
      containers:
        - name: react-preview
          image: syeddhasnainn/react-preview:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5173
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 500Mi
            limits:
              cpu: 100m
              memory: 500Mi